name: sazarcode
description: My personal website design with Material Design.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  appflowy_editor: ^1.2.4
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4

  flutter:
    sdk: flutter

  flutter_markdown: ^0.6.17
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  provider: ^6.0.5
  super_editor: ^0.2.6
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
