name: cerberusprogrammer
description: My personal web.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.1
  adaptive_theme: ^3.2.1
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  icons_plus: ^4.0.0
  url_launcher: ^6.1.11
  go_router: ^8.1.0
  provider: ^6.0.5
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  flutter_markdown: ^0.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/nutriplato/
    - lib/assets/enfo/
    - lib/assets/inspireme/
    - lib/assets/wtd/